// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhZLZRfRzY_HH-XDHYnfncGbY0GeSNz_s',
    appId: '1:388179869926:web:e1ac2ab8d2643798dbbb27',
    messagingSenderId: '388179869926',
    projectId: 'earnest-assignment',
    authDomain: 'earnest-assignment.firebaseapp.com',
    storageBucket: 'earnest-assignment.appspot.com',
    measurementId: 'G-E74XSCH5CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDxf7k4KsNG0cwTi27jzNN2CIXCBhgqE',
    appId: '1:388179869926:android:d641bed169c2c630dbbb27',
    messagingSenderId: '388179869926',
    projectId: 'earnest-assignment',
    storageBucket: 'earnest-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0eggeWqU9A9LfkC0qqQubu4H4yZ0vMzQ',
    appId: '1:388179869926:ios:ca40f74518b47fa5dbbb27',
    messagingSenderId: '388179869926',
    projectId: 'earnest-assignment',
    storageBucket: 'earnest-assignment.appspot.com',
    iosBundleId: 'com.example.earnestAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0eggeWqU9A9LfkC0qqQubu4H4yZ0vMzQ',
    appId: '1:388179869926:ios:ca40f74518b47fa5dbbb27',
    messagingSenderId: '388179869926',
    projectId: 'earnest-assignment',
    storageBucket: 'earnest-assignment.appspot.com',
    iosBundleId: 'com.example.earnestAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhZLZRfRzY_HH-XDHYnfncGbY0GeSNz_s',
    appId: '1:388179869926:web:a2ac2412755cf8ebdbbb27',
    messagingSenderId: '388179869926',
    projectId: 'earnest-assignment',
    authDomain: 'earnest-assignment.firebaseapp.com',
    storageBucket: 'earnest-assignment.appspot.com',
    measurementId: 'G-TXYQLJ6LXH',
  );
}
